config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  get '/restaurants', to: 'homes#index'
  get '/restaurants/:id/reviews/new', to: 'homes#index'
  get '/restaurants/:id', to: 'homes#index'
  get '/u/:username', to: 'homes#index'
  get '/recipes', to: 'homes#index'
  get '/recipes/:id', to: 'homes#index'
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:show]
      resources :restaurants, only: [:show] do
        resources :reviews, only: [:create]
      end
      post '/restaurants/search', to: 'restaurants#search'
      post '/recipes/search', to: 'recipes#search'
      resources :reviews, only: [:update, :destroy] do
        resources :review_likes, only: [:create]
      end
      resources :recipes, only: [:show]
    end
  end

end

# Future work for liked restaurant
# POST api/v1/reviews/1/review_likes
# params - review id
# controller - current_user

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :rating, presence: true

  belongs_to :user

  has_many :review_likes

  mount_uploader :photo, ReviewPhotoUploader
end

app/models/review_like.rb
class ReviewLike < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/services/yelp_service.rb
require "json"
require "dotenv"
require "http"
require "optparse"

Dotenv.load

class YelpService

API_HOST = "https://api.yelp.com"
SEARCH_PATH = "/v3/businesses/search"
BUSINESS_PATH = "/v3/businesses/"
SEARCH_LIMIT = 20

API_KEY = ENV["YELP_API_KEY"]

def self.search(location = 'Boston, MA', term = 'pizza')
  url = "#{API_HOST}#{SEARCH_PATH}"
  params = {
    location: location,
    term: term,
    limit: SEARCH_LIMIT
  }

  response = HTTP.auth("Bearer #{API_KEY}").get(url, params: params)
  response.parse
end

def self.business(business_id)
  url = "#{API_HOST}#{BUSINESS_PATH}#{business_id}"

  response = HTTP.auth("Bearer #{API_KEY}").get(url)
  response.parse
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true

  mount_uploader :profile_photo, ProfilePhotoUploader
  
  has_many :reviews
  has_many :review_likes
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApiController

  API_KEY = ENV["SPOONACULAR_API_KEY"]

  def search
    url = "https://api.spoonacular.com/recipes/complexSearch?apiKey=#{API_KEY}&query=#{params[:item]}"

    response = Faraday.get(url)
      
    search_recipes_hash = JSON.parse(response.body)

    if !search_recipes_hash.nil?
      returned_recipe = search_recipes_hash["results"].sample(4)

      recipe_featured = returned_recipe[0]
      recipe_others = returned_recipe[1..-1]

      render json: {recipe_featured: recipe_featured, recipe_others: recipe_others}
    else
      render json: {error: "error"}, status: 404
    end
  end

  def show
    url = "https://api.spoonacular.com/recipes/#{params[:id]}/information?apiKey=#{API_KEY}"
    response = Faraday.get(url)

    recipe = JSON.parse(response.body)
    render json: {recipe: recipe}

  end

  private 
  
  def search_params
    params.require(:recipe).permit(:item)
  end

end

app/controllers/api/v1/restaurants_controller.rb
class Api::V1::RestaurantsController < ApiController

  def show
    search_restaurant_hash = YelpService.business(params[:id])
    reviews = Review.where(yelp_restaurant_id: params[:id])

    render json: {
      restaurant: search_restaurant_hash,
      current_user: current_user,
      reviews: ActiveModelSerializers::SerializableResource.new(reviews, each_serializer: ReviewSerializer, scope: current_user)
    }
  end

  def search
    
    search_result_hash = YelpService.search(search_params[:location], search_params[:item])
    search_result_restaurants_array = search_result_hash["businesses"]

    if !search_result_restaurants_array.nil?
      returned_restaurant = search_result_restaurants_array.sample(4)
      
      restaurant_featured = returned_restaurant[0]
      restaurant_others = returned_restaurant[1..-1]
      render json: { restaurant_featured: restaurant_featured, restaurant_others: restaurant_others }
    else
      render json: search_result_hash["error"], status: 404
    end
  end

  private

  def search_params
    params.require(:restaurant).permit(:location,:item)
  end
  
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController
  before_action :authenticate_user, only: [:create]
  skip_before_action :verify_authenticity_token

  def create
    review = Review.new(review_params)
    review.user = current_user

    if review.save
      render json: review
    else
      render json: {errors: review.errors.full_messages.to_sentence}
    end

  end

  def update
    review = Review.find(params[:id])

    if review.update(review_params)
      render json: review
    else  
      render json: {errors: review.errors.full_messages.to_sentence}
    end

  end

  def destroy
    review = Review.find(params[:id])

    if review.destroy
    render json: {delete: "review deleted successfully"}
    else 
      render json: {errors: review.errors.full_messages.to_sentence}
    end
  end

  private
  def review_params
    params.permit(:title, :description, :rating, :photo, :yelp_restaurant_id)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController

  def show
    user = User.find_by(username: params[:id])
    render json: user, serializer: UserSerializer
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  protected

  def authorize_admin
    if !user_signed_in? || !(current_user.role == "admin")
      render json: {error: ["Only admins have access to this feature"]}
    end
  end

  def authenticate_user
    if !user_signed_in?
      render json: {error: ["You need to be signed in first"]}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ApiController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profile_photo])
  end

  def after_sign_in_path_for(resource)
    restaurants_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def authorized  
  end

  def authenticated  
  end

end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/homes/index.html.erb
<div id="app">
    
</div>

app/views/layouts/_extra_footer.html.erb
<div class="footer">
  <a href="https://www.linkedin.com/in/danielfanpro/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
  <a href="https://github.com/danielfan-pro/foodle" target="_blank"><i class="fa-brands fa-github"></i></a>
  <a href="mailto:danielfanpro@icloud.com"><i class="fa-solid fa-envelope"></i></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodle</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= render 'application/favicon' %>
  <script src="https://kit.fontawesome.com/93f0a04255.js" crossorigin="anonymous"></script>
</head>
<body>
  
  <nav class="top-bar">

    <div class="left">
      <a href="/"><%= image_tag("foodle transparent.png", alt: "logo", :class => "logo-nav-bar") %></a>
      <%= link_to 'Restaurants', restaurants_path, :class => "button hollow" %>
      <%= link_to 'Recipes', recipes_path, :class => "button hollow" %>
    </div>

    <div>
      <% default_profile = '/Default-profile.png' %>

      <div class="top-bar-section">
        <ul class="right">
          <%- if current_user && current_user[:profile_photo].nil? == false-%>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => "button hollow"%>
            <a href='/u/<%= current_user.username %>'><img class="profile-icon" src='<%= current_user.profile_photo %>' /></a>
           <%- elsif current_user && current_user[:profile_photo].nil? -%>  
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => "button hollow"%>
              <a href='/u/<%= current_user.username %>'><img class="profile-icon" src='<%= default_profile %>' /></a>
          <%- else -%>
            <%= link_to 'Sign In', new_user_session_path, :class => "button hollow" %>
          <%- end -%>
        </ul>
      </div>

    </div>

  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= render "layouts/extra_footer" %>
</body>
</html>